name: model_practice
channels:
  - defaults
  - conda-forge
  - plotly

dependencies:
  - python=3.10
  - pip

  # custom reqs
  - ipython
  - isort
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - nbstripout
  - pandas
  - plotly
  - pytest-cov
  - pytest-mock
  - pytest
  - seaborn
  - scikit-learn
 




